targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          # auto registers any class with a name matches the given pattern
          class_name_pattern:
            "Service$|Repository$|Bloc$|Cubit$|UseCase$|Action$|Reaction$"
            # auto registers any class inside a file with a
            # name matches the given pattern
          file_name_pattern: "_service$|_repository$|_bloc$|cubit$|use_case$|action$|reaction$"
