name: flow_todo_flutter_2022
description: A new Flutter project.
publish_to: "none"

version: 1.4.6

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0
  meta: ^1.7.0
  build_context_provider: ^1.0.0
  google_sign_in: ^5.3.2
  cloud_firestore: ^3.1.17
  uuid: ^3.0.6
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  reactive_forms: ^13.0.0
  freezed_annotation: ^2.0.3
  liquid_progress_indicator: ^0.4.0
  extended_image: ^6.2.1
  water_drop_nav_bar: ^2.2.0+3
  path_provider: ^2.0.11
  flex_color_scheme: ^5.0.1
  percent_indicator: ^4.2.2
  injectable: ^1.5.3
  countup: ^0.1.4
  flutter_hooks: ^0.18.5+1
  memoize: ^3.0.0
  timeago: ^3.2.2
  easy_debounce: ^2.0.2+1
  fuzzywuzzy: ^0.2.0
  remove_emoji: ^0.0.7
  bloc: ^8.0.3
  replay_bloc: ^0.2.1
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^9.0.0-dev.2
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  firebase_analytics: ^9.3.0
  firebase_crashlytics: ^2.8.7
  firebase_performance: ^0.8.2+4
  firebase_remote_config: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^0.3.0
  bloc_test: ^9.0.3
  freezed: ^2.0.3+1
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  dart_code_metrics: ^4.15.2
  fake_cloud_firestore: ^1.2.2
  injectable_generator: ^1.5.3

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
